#############################################################################
# Makefile for building: Channel_2x2
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Mar 19 20:16:49 2014
# Project:  Channel_2x2.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.1/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++ -o Makefile Channel_2x2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.8.1/include/QtCore -I/usr/local/Trolltech/Qt-4.8.1/include/QtGui -I/usr/local/Trolltech/Qt-4.8.1/include/QtOpenGL -I/usr/local/Trolltech/Qt-4.8.1/include -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.1/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.1/lib -L/usr/X11R6/lib -lQtOpenGL -L/usr/local/Trolltech/Qt-4.8.1/lib -L/usr/X11R6/lib64 -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.1/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		subwindow.cpp \
		channelh11.cpp \
		channelh12.cpp \
		channelh21.cpp \
		channelh22.cpp \
		channel2d.cpp \
		ch2_1.cpp \
		ch2_2.cpp \
		multiwindow.cpp moc_subwindow.cpp \
		moc_multiwindow.cpp
OBJECTS       = main.o \
		subwindow.o \
		channelh11.o \
		channelh12.o \
		channelh21.o \
		channelh22.o \
		channel2d.o \
		ch2_1.o \
		ch2_2.o \
		multiwindow.o \
		moc_subwindow.o \
		moc_multiwindow.o
DIST          = /usr/local/Trolltech/Qt-4.8.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/include_source_dir.prf \
		Channel_2x2.pro
QMAKE_TARGET  = Channel_2x2
DESTDIR       = 
TARGET        = Channel_2x2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_subwindow.h ui_channelh11.h ui_channelh12.h ui_channelh21.h ui_channelh22.h ui_channel2d.h ui_ch2_1.h ui_ch2_2.h ui_multiwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Channel_2x2.pro  /usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.1/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.1/lib/libQtOpenGL.prl \
		/usr/local/Trolltech/Qt-4.8.1/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.1/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++ -o Makefile Channel_2x2.pro
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/opengl.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.1/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.1/lib/libQtOpenGL.prl:
/usr/local/Trolltech/Qt-4.8.1/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.1/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.1/mkspecs/linux-g++ -o Makefile Channel_2x2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Channel_2x21.0.0 || $(MKDIR) .tmp/Channel_2x21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Channel_2x21.0.0/ && $(COPY_FILE) --parents subwindow.h channelh11.h channelh12.h channelh21.h channelh22.h channel2d.h ch2_1.h ch2_2.h multiwindow.h .tmp/Channel_2x21.0.0/ && $(COPY_FILE) --parents main.cpp subwindow.cpp channelh11.cpp channelh12.cpp channelh21.cpp channelh22.cpp channel2d.cpp ch2_1.cpp ch2_2.cpp multiwindow.cpp .tmp/Channel_2x21.0.0/ && $(COPY_FILE) --parents subwindow.ui channelh11.ui channelh12.ui channelh21.ui channelh22.ui channel2d.ui ch2_1.ui ch2_2.ui multiwindow.ui .tmp/Channel_2x21.0.0/ && (cd `dirname .tmp/Channel_2x21.0.0` && $(TAR) Channel_2x21.0.0.tar Channel_2x21.0.0 && $(COMPRESS) Channel_2x21.0.0.tar) && $(MOVE) `dirname .tmp/Channel_2x21.0.0`/Channel_2x21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Channel_2x21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_subwindow.cpp moc_multiwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_subwindow.cpp moc_multiwindow.cpp
moc_subwindow.cpp: subwindow.h
	/usr/local/Trolltech/Qt-4.8.1/bin/moc $(DEFINES) $(INCPATH) subwindow.h -o moc_subwindow.cpp

moc_multiwindow.cpp: multiwindow.h
	/usr/local/Trolltech/Qt-4.8.1/bin/moc $(DEFINES) $(INCPATH) multiwindow.h -o moc_multiwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_subwindow.h ui_channelh11.h ui_channelh12.h ui_channelh21.h ui_channelh22.h ui_channel2d.h ui_ch2_1.h ui_ch2_2.h ui_multiwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_subwindow.h ui_channelh11.h ui_channelh12.h ui_channelh21.h ui_channelh22.h ui_channel2d.h ui_ch2_1.h ui_ch2_2.h ui_multiwindow.h
ui_subwindow.h: subwindow.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic subwindow.ui -o ui_subwindow.h

ui_channelh11.h: channelh11.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic channelh11.ui -o ui_channelh11.h

ui_channelh12.h: channelh12.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic channelh12.ui -o ui_channelh12.h

ui_channelh21.h: channelh21.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic channelh21.ui -o ui_channelh21.h

ui_channelh22.h: channelh22.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic channelh22.ui -o ui_channelh22.h

ui_channel2d.h: channel2d.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic channel2d.ui -o ui_channel2d.h

ui_ch2_1.h: ch2_1.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic ch2_1.ui -o ui_ch2_1.h

ui_ch2_2.h: ch2_2.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic ch2_2.ui -o ui_ch2_2.h

ui_multiwindow.h: multiwindow.ui
	/usr/local/Trolltech/Qt-4.8.1/bin/uic multiwindow.ui -o ui_multiwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp channelh11.h \
		channel2d.h \
		multiwindow.h \
		ch2_1.h \
		ch2_2.h \
		subwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

subwindow.o: subwindow.cpp subwindow.h \
		ui_subwindow.h \
		channelh11.h \
		channelh12.h \
		channelh21.h \
		channelh22.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o subwindow.o subwindow.cpp

channelh11.o: channelh11.cpp channelh11.h \
		ui_channelh11.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o channelh11.o channelh11.cpp

channelh12.o: channelh12.cpp channelh12.h \
		ui_channelh12.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o channelh12.o channelh12.cpp

channelh21.o: channelh21.cpp channelh21.h \
		ui_channelh21.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o channelh21.o channelh21.cpp

channelh22.o: channelh22.cpp channelh22.h \
		ui_channelh22.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o channelh22.o channelh22.cpp

channel2d.o: channel2d.cpp channel2d.h \
		ui_channel2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o channel2d.o channel2d.cpp

ch2_1.o: ch2_1.cpp ch2_1.h \
		ui_ch2_1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ch2_1.o ch2_1.cpp

ch2_2.o: ch2_2.cpp ch2_2.h \
		ui_ch2_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ch2_2.o ch2_2.cpp

multiwindow.o: multiwindow.cpp multiwindow.h \
		ui_multiwindow.h \
		ch2_1.h \
		ch2_2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multiwindow.o multiwindow.cpp

moc_subwindow.o: moc_subwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_subwindow.o moc_subwindow.cpp

moc_multiwindow.o: moc_multiwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_multiwindow.o moc_multiwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

